<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="ag1_base">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="0.3" /> <!-- TODO: Fixme -->
  <xacro:property name="base_width" value="0.35" />
  <xacro:property name="base_length" value="-1.0" />
  <!-- <xacro:property name="base_length" value="0.5" /> -->

  <xacro:property name="base_height" value="0.25" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- TODO: Fixme -->
  <xacro:property name="wheel_len" value="0.080" />
  <xacro:property name="wheel_radius" value="0.128" />
  <xacro:property name="caster_wheel_mass" value="0.1" /> <!-- TODO: Fixme -->
  <xacro:property name="caster_wheel_radius" value="0.128" />

  <xacro:property name="oak_z" value ="0.5"/>
  <xacro:property name="oak_x" value ="0.15"/>
  <xacro:property name="oak_r" value ="0.0"/>
  <xacro:property name="oak_p" value ="0.54"/>

  <link name="base_footprint" />

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <collision>
      <origin xyz="${3*base_length/8} 0 ${wheel_radius}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${3*base_length/8} 0 ${wheel_radius}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_wheel"/>
      <origin xyz="0 ${-base_width/2 - wheel_len/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>

      <dynamics damping="0.2"/>
    </joint>

    <link name="right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_wheel"/>
      <origin xyz="0 ${base_width/2 + wheel_len/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <link name="left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <joint name="caster_left_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_left_wheel"/>
      <origin xyz="${3*base_length/4} ${base_width/2} ${caster_wheel_radius - wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="caster_left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
      </link>

    <joint name="caster_right_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_right_wheel"/>
      <origin xyz="${3*base_length/4} -${base_width/2} ${caster_wheel_radius - wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="caster_right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
    </link>

      <!-- start -->
       <!-- *********************** IMU SETUP *********************************  -->
  <!--Each sensor must be attached to a link.        -->
  
                    
  
    <joint name="imu_joint" type="fixed">
      <parent link="base_link"/>
      <child link="imu_link"/>
      <origin xyz="-0.00 0 0.2" rpy="0 0 0"/>
    </joint>

    <link name="imu_link">
  <visual name="">
              <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
              <geometry>
                  <cylinder radius="0.1" length="0.1"/>
              </geometry>
              <material name="not_purple">
                  <color rgba="0.0 0.0 1.0 1.0"/>
                  <texture filename=""/>
              </material>
          </visual>
      </link>
  <!-- *********************** GPS SETUP **********************************  -->
    <joint name="gps_joint" type="fixed">
      <parent link="base_link"/>
      <child link="gps_link"/>
      <origin xyz="0.0 0 0.8" rpy="0 0 0"/>
    </joint>

    <link name="gps_link">
      <visual name="">
              <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
              <geometry>
                  <cylinder radius="0.1" length="0.1"/>
              </geometry>
              <material name="purple">
                  <color rgba="1.0 0.0 1.0 1.0"/>
                  <texture filename=""/>
              </material>
        </visual>
    </link>
    

    <!-- *********************** Camera SETUP **********************************  -->
    <joint name="camera_joint" type="fixed">
      <parent link="base_link"/>
      <child link="camera_link"/>
      <origin xyz="0.4 0 0.8" rpy="0 0.18 0"/>
    </joint>

    <link name="camera_link">
      <visual name="">
              <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
              <geometry>
                  <cylinder radius="0.1" length="0.1"/>
              </geometry>
              <material name="white">
                  <color rgba="1.0 0.0 1.0 1.0"/>
                  <texture filename=""/>
              </material>
        </visual>
    </link>
    <!-- *********************** OAK SETUP **********************************  -->
    <joint name="oak_joint" type="fixed">
      <parent link="base_link"/>
      <child link="oak_link"/>
      <origin xyz="${oak_x} 0 ${oak_z}" rpy="${oak_r} ${oak_p} 0"/>
    </joint>

    <link name="oak_link">
      <visual name="">
          <origin xyz="0. 0.0 0.0" rpy="0.0 0.0 0.0"/>
          <geometry>
              <!-- <cylinder radius="0.1" length="0.1"/> -->
              <box size=".1 .4 .1"/>
          </geometry>
          <material name="notsure">
              <color rgba="0.5 0.5 0.5 1.0"/>
              <texture filename=""/>
          </material>
      </visual>
    </link>

        <!-- oak optical -->
    <joint name="oak_opt_joint" type="fixed">
        <parent link="oak_link"/>
        <!-- <child link="oak_opt_link"/> -->
        <child link="oak-d-base-frame"/>
        <origin xyz=".1 0 0 " rpy="${0*pi/2} ${-pi/10} ${0*pi/2}"/>
    </joint>

      <!-- <link name="oak_opt_link"> -->
    <link name="oak-d-base-frame">
        <visual name="">
            <origin xyz="0. 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="0.1"/>
                <!-- <box size=".1 .4 .1"/> -->
            </geometry>
            <material name="notsure">
                <color rgba="1.0 0.5 0.5 1.0"/>
                <texture filename=""/>
            </material>
        </visual>
    </link>


      <!-- end -->

  </xacro:macro>

</robot>